# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "differ"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pieter van de Bruggen"]
  s.date = "2012-04-16"
  s.email = "pvande@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "differ.gemspec",
    "lib/differ.rb",
    "lib/differ/change.rb",
    "lib/differ/diff.rb",
    "lib/differ/format/ascii.rb",
    "lib/differ/format/color.rb",
    "lib/differ/format/html.rb",
    "lib/differ/format/passage.rb",
    "lib/differ/string.rb",
    "spec/differ/change_spec.rb",
    "spec/differ/diff_spec.rb",
    "spec/differ/format/ascii_spec.rb",
    "spec/differ/format/color_spec.rb",
    "spec/differ/format/html_spec.rb",
    "spec/differ/string_spec.rb",
    "spec/differ_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/pvande/differ"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A simple gem for generating string diffs"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

